# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python image with uv pre-installed
FROM python:3.11-slim as uv


# Set the working directory
WORKDIR /app

RUN pip install uv


# Copy the necessary files
COPY pyproject.toml uv.lock ./

# Install the project's dependencies
RUN --mount=type=cache,target=/root/.cache/uv uv sync --frozen --no-dev --no-editable

# Copy the rest of the application files
COPY . .


# Expose the port that the server will run on
EXPOSE 8080

# Default command to run the server
CMD ["uv", "run", "weather.py"]
